{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0ff05a20-d25d-4b99-a0be-42f2d4a5b331",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import scrolledtext\n",
    "import datetime\n",
    "import re\n",
    "\n",
    "# ---------------------------\n",
    "# Knowledge Base (Domain Q&A)\n",
    "# ---------------------------\n",
    "knowledge_base = {\n",
    "    \"what is ai\": \"AI (Artificial Intelligence) is the simulation of human intelligence in machines.\",\n",
    "    \"what is artificial intelligence\": \"Artificial Intelligence is the field of creating machines that can perform tasks requiring human intelligence.\",\n",
    "    \"what is machine learning\": \"Machine Learning is a subset of AI that allows systems to learn from data.\",\n",
    "    \"what is deep learning\": \"Deep Learning is a type of machine learning based on neural networks with many layers.\",\n",
    "    \"what is a neural network\": \"A neural network is a system of algorithms inspired by the human brain.\",\n",
    "    \"what is supervised learning\": \"Supervised learning uses labeled data to train models.\",\n",
    "    \"what is unsupervised learning\": \"Unsupervised learning finds patterns in data without labels.\",\n",
    "    \"what is reinforcement learning\": \"Reinforcement learning trains agents using rewards and penalties.\",\n",
    "    \"what is natural language processing\": \"NLP enables computers to understand human language.\",\n",
    "    \"what is computer vision\": \"Computer vision allows machines to interpret visual information from images and videos.\",\n",
    "    \"what is data science\": \"Data science involves extracting insights from data using scientific methods.\",\n",
    "    \"what is a dataset\": \"A dataset is a collection of data used for analysis or training models.\",\n",
    "    \"what is training data\": \"Training data is used to teach machine learning models.\",\n",
    "    \"what is testing data\": \"Testing data evaluates how well a model performs.\",\n",
    "    \"what is overfitting\": \"Overfitting occurs when a model learns training data too well and fails on new data.\",\n",
    "    \"what is underfitting\": \"Underfitting occurs when a model fails to capture patterns in the data.\",\n",
    "    \"what is model accuracy\": \"Accuracy measures how often a model makes correct predictions.\",\n",
    "    \"what is precision\": \"Precision measures how many predicted positives are actually correct.\",\n",
    "    \"what is recall\": \"Recall measures how many actual positives are correctly identified.\",\n",
    "    \"what is f1 score\": \"F1 score balances precision and recall.\",\n",
    "    \"what is classification\": \"Classification assigns data into predefined categories.\",\n",
    "    \"what is regression\": \"Regression predicts continuous numerical values.\",\n",
    "    \"what is clustering\": \"Clustering groups similar data points together.\",\n",
    "    \"what is feature engineering\": \"Feature engineering involves creating useful input variables for models.\",\n",
    "    \"what is a feature\": \"A feature is an input variable used by a model.\",\n",
    "    \"what is a label\": \"A label is the output variable a model predicts.\",\n",
    "    \"what is ai ethics\": \"AI ethics studies moral issues related to AI development and use.\",\n",
    "    \"what is explainable ai\": \"Explainable AI makes model decisions understandable to humans.\",\n",
    "    \"what is generative ai\": \"Generative AI creates new content such as text, images, or music.\",\n",
    "    \"what is a chatbot\": \"A chatbot is a program that simulates conversation with users.\",\n",
    "    \"what is a language model\": \"A language model predicts and generates human-like text.\",\n",
    "    \"what is gpt\": \"GPT is a type of language model designed for generating text.\",\n",
    "    \"what is automation\": \"Automation uses technology to perform tasks without human intervention.\",\n",
    "    \"what is robotics\": \"Robotics involves designing and building intelligent machines.\",\n",
    "    \"what is edge ai\": \"Edge AI runs AI algorithms locally on devices instead of the cloud.\",\n",
    "    \"what is cloud ai\": \"Cloud AI uses remote servers to process AI tasks.\",\n",
    "    \"what is big data\": \"Big data refers to extremely large datasets analyzed computationally.\",\n",
    "    \"what is data mining\": \"Data mining discovers patterns in large datasets.\",\n",
    "    \"what is transfer learning\": \"Transfer learning reuses knowledge from one task for another.\",\n",
    "    \"what is fine tuning\": \"Fine tuning adapts a pretrained model to a specific task.\",\n",
    "    \"what is a pretrained model\": \"A pretrained model is trained on large datasets before being reused.\",\n",
    "    \"what is ai bias\": \"AI bias occurs when models produce unfair results due to biased data.\",\n",
    "    \"what is model deployment\": \"Deployment means putting a trained model into real-world use.\",\n",
    "    \"what is inference\": \"Inference is using a trained model to make predictions.\",\n",
    "    \"what is hyperparameter\": \"A hyperparameter controls how a model learns.\",\n",
    "    \"what is gradient descent\": \"Gradient descent is an optimization method for training models.\",\n",
    "    \"what is loss function\": \"A loss function measures model prediction error.\",\n",
    "    \"what is backpropagation\": \"Backpropagation updates neural network weights during training.\",\n",
    "    \"what is a tensor\": \"A tensor is a multidimensional array used in deep learning.\",\n",
    "    \"what is pytorch\": \"PyTorch is a popular deep learning framework.\",\n",
    "    \"what is tensorflow\": \"TensorFlow is an open-source machine learning library.\",\n",
    "    \"what is keras\": \"Keras is a high-level neural network API.\",\n",
    "    \"what is scikit learn\": \"Scikit-learn is a machine learning library for Python.\",\n",
    "    \"what is pandas\": \"Pandas is a Python library for data manipulation.\",\n",
    "    \"what is numpy\": \"NumPy is a library for numerical computing in Python.\",\n",
    "    \"what is data preprocessing\": \"Data preprocessing cleans and prepares data for modeling.\",\n",
    "    \"what is normalization\": \"Normalization scales data to a standard range.\",\n",
    "    \"what is standardization\": \"Standardization rescales data to have mean zero and unit variance.\",\n",
    "    \"what is cross validation\": \"Cross validation evaluates models using multiple data splits.\",\n",
    "    \"what is confusion matrix\": \"A confusion matrix shows prediction performance by class.\",\n",
    "    \"what is anomaly detection\": \"Anomaly detection identifies unusual patterns in data.\",\n",
    "    \"what is recommendation system\": \"A recommendation system suggests items to users.\",\n",
    "    \"what is speech recognition\": \"Speech recognition converts spoken language into text.\",\n",
    "    \"what is text to speech\": \"Text-to-speech converts written text into spoken audio.\",\n",
    "    \"what is sentiment analysis\": \"Sentiment analysis determines emotion in text.\",\n",
    "    \"what is topic modeling\": \"Topic modeling identifies themes in documents.\",\n",
    "    \"what is object detection\": \"Object detection identifies objects in images.\",\n",
    "    \"what is image classification\": \"Image classification assigns labels to images.\",\n",
    "    \"what is segmentation\": \"Segmentation divides images into meaningful parts.\",\n",
    "    \"what is autonomous vehicle\": \"Autonomous vehicles use AI to drive without humans.\",\n",
    "    \"what is smart assistant\": \"A smart assistant is an AI that helps users via voice or text.\",\n",
    "    \"what is turing test\": \"The Turing Test evaluates whether a machine can mimic human intelligence.\",\n",
    "    \"what is artificial general intelligence\": \"AGI refers to machines with human-level intelligence.\",\n",
    "    \"what is artificial superintelligence\": \"ASI refers to intelligence beyond human capability.\",\n",
    "    \"what is ai safety\": \"AI safety ensures AI systems operate without causing harm.\",\n",
    "    \"what is ai governance\": \"AI governance involves policies for responsible AI use.\",\n",
    "    \"what is federated learning\": \"Federated learning trains models across multiple devices.\",\n",
    "    \"what is multi agent system\": \"Multi-agent systems involve multiple interacting AI agents.\",\n",
    "    \"what is swarm intelligence\": \"Swarm intelligence is collective behavior of decentralized systems.\",\n",
    "    \"what is evolutionary algorithm\": \"Evolutionary algorithms use natural selection concepts.\",\n",
    "    \"what is genetic algorithm\": \"Genetic algorithms solve problems using evolution principles.\",\n",
    "    \"what is simulated annealing\": \"Simulated annealing is an optimization technique.\",\n",
    "    \"what is knowledge representation\": \"Knowledge representation stores information for AI reasoning.\",\n",
    "    \"what is expert system\": \"An expert system mimics decision-making of human experts.\",\n",
    "    \"what is rule based system\": \"A rule-based system uses predefined rules to make decisions.\",\n",
    "    \"what is symbolic ai\": \"Symbolic AI uses logic and rules to represent knowledge.\",\n",
    "    \"what is subsymbolic ai\": \"Subsymbolic AI uses neural networks and statistics.\",\n",
    "    \"what is hybrid ai\": \"Hybrid AI combines symbolic and subsymbolic methods.\",\n",
    "    \"what is ai application\": \"AI applications include healthcare, finance, education, and more.\",\n",
    "    \"what is ai in healthcare\": \"AI helps diagnose diseases and analyze medical data.\",\n",
    "    \"what is ai in education\": \"AI personalizes learning experiences for students.\",\n",
    "    \"what is ai in business\": \"AI improves decision-making and automation in business.\",\n",
    "    \"what is ai in gaming\": \"AI controls non-player characters and game behavior.\",\n",
    "    \"what is ai in cybersecurity\": \"AI detects threats and prevents cyber attacks.\",\n",
    "    \"what is ai future\": \"AI will continue transforming industries and daily life.\",\n",
    "    \"who created python\": \"Python was created by Guido van Rossum.\",\n",
    "    \"what is your name\": \"I am a Rule-Based Chatbot.\",\n",
    "    \"where are you from\": \"I live inside your computer!\"\n",
    "}\n",
    "\n",
    "# ---------------------------\n",
    "# Intent Patterns & Responses\n",
    "# ---------------------------\n",
    "patterns = {\n",
    "    \"greeting\": {\n",
    "        \"patterns\": [r\"\\bhi\\b\", r\"\\bhello\\b\", r\"\\bhey\\b\"],\n",
    "        \"responses\": [\"Hello!\", \"Hi there!\", \"Hey! How can I help you?\"]\n",
    "    },\n",
    "    \"help\": {\n",
    "        \"patterns\": [r\"\\bhelp\\b\", r\"\\bassist\\b\", r\"\\bsupport\\b\"],\n",
    "        \"responses\": [\"I can answer basic questions about AI, Python, and chat with you.\"]\n",
    "    },\n",
    "    \"smalltalk\": {\n",
    "        \"patterns\": [r\"how are you\", r\"what's up\", r\"how's it going\"],\n",
    "        \"responses\": [\"I'm just a bot, but I'm doing great!\", \"All good here!\"]\n",
    "    },\n",
    "    \"bye\": {\n",
    "        \"patterns\": [r\"\\bbye\\b\", r\"goodbye\", r\"see you\"],\n",
    "        \"responses\": [\"Goodbye!\", \"See you later!\", \"Bye!\"]\n",
    "    }\n",
    "}\n",
    "\n",
    "# ---------------------------\n",
    "# Chatbot Logic\n",
    "# ---------------------------\n",
    "def get_response(user_input):\n",
    "    text = user_input.lower()\n",
    "\n",
    "    # Check knowledge base\n",
    "    for question in knowledge_base:\n",
    "        if question in text:\n",
    "            return knowledge_base[question]\n",
    "\n",
    "    # Check intents\n",
    "    for intent in patterns:\n",
    "        for pattern in patterns[intent][\"patterns\"]:\n",
    "            if re.search(pattern, text):\n",
    "                return patterns[intent][\"responses\"][0]\n",
    "\n",
    "    return \"Sorry, I don't understand that.\"\n",
    "\n",
    "# ---------------------------\n",
    "# Logging Function\n",
    "# ---------------------------\n",
    "def log_conversation(user, bot):\n",
    "    with open(\"chat_history.txt\", \"a\") as f:\n",
    "        time = datetime.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "        f.write(f\"[{time}] User: {user}\\n\")\n",
    "        f.write(f\"[{time}] Bot: {bot}\\n\")\n",
    "\n",
    "# ---------------------------\n",
    "# Console Mode (Optional)\n",
    "# ---------------------------\n",
    "def console_chat():\n",
    "    print(\"Chatbot started (type 'exit' to quit)\")\n",
    "    while True:\n",
    "        user = input(\"You: \")\n",
    "        if user.lower() == \"exit\":\n",
    "            break\n",
    "        bot = get_response(user)\n",
    "        print(\"Bot:\", bot)\n",
    "        log_conversation(user, bot)\n",
    "\n",
    "# ---------------------------\n",
    "# GUI Application\n",
    "# ---------------------------\n",
    "def send_message():\n",
    "    user_input = entry.get()\n",
    "    if user_input.strip() == \"\":\n",
    "        return\n",
    "\n",
    "    chat_area.insert(tk.END, \"You: \" + user_input + \"\\n\")\n",
    "    bot_response = get_response(user_input)\n",
    "    chat_area.insert(tk.END, \"Bot: \" + bot_response + \"\\n\\n\")\n",
    "\n",
    "    log_conversation(user_input, bot_response)\n",
    "    entry.delete(0, tk.END)\n",
    "    chat_area.yview(tk.END)\n",
    "\n",
    "# ---------------------------\n",
    "# GUI Window\n",
    "# ---------------------------\n",
    "root = tk.Tk()\n",
    "root.title(\"Rule-Based Chatbot\")\n",
    "root.geometry(\"500x600\")\n",
    "\n",
    "chat_area = scrolledtext.ScrolledText(root, wrap=tk.WORD, font=(\"Arial\", 12))\n",
    "chat_area.pack(padx=10, pady=10, fill=tk.BOTH, expand=True)\n",
    "\n",
    "entry = tk.Entry(root, font=(\"Arial\", 14))\n",
    "entry.pack(padx=10, pady=10, fill=tk.X)\n",
    "\n",
    "send_button = tk.Button(root, text=\"Send\", command=send_message)\n",
    "send_button.pack(pady=5)\n",
    "\n",
    "# Press Enter to send\n",
    "root.bind('<Return>', lambda event: send_message())\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "164f4f7e-c5c5-4956-9be3-fe1271970de1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
